// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAD1JpJhlA85N6wymEbXT87LkPPa-UWF98',
    appId: '1:595367138806:web:add7cf450a7cccaad5a3d7',
    messagingSenderId: '595367138806',
    projectId: 'finace-app-d638b',
    authDomain: 'finace-app-d638b.firebaseapp.com',
    storageBucket: 'finace-app-d638b.firebasestorage.app',
    measurementId: 'G-SL3KT6W64M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmGdV7ZKk8PttuR-SRi6lH4xQ1kvJAXJA',
    appId: '1:595367138806:android:9779da4e8815ceb0d5a3d7',
    messagingSenderId: '595367138806',
    projectId: 'finace-app-d638b',
    storageBucket: 'finace-app-d638b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQmtP83sUOGvbm0AHvqRvDw9qtkQpg0CU',
    appId: '1:595367138806:ios:e4ea163a1dbd406dd5a3d7',
    messagingSenderId: '595367138806',
    projectId: 'finace-app-d638b',
    storageBucket: 'finace-app-d638b.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQmtP83sUOGvbm0AHvqRvDw9qtkQpg0CU',
    appId: '1:595367138806:ios:e4ea163a1dbd406dd5a3d7',
    messagingSenderId: '595367138806',
    projectId: 'finace-app-d638b',
    storageBucket: 'finace-app-d638b.firebasestorage.app',
    iosBundleId: 'com.example.financeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAD1JpJhlA85N6wymEbXT87LkPPa-UWF98',
    appId: '1:595367138806:web:0364ccbc65fb3cc2d5a3d7',
    messagingSenderId: '595367138806',
    projectId: 'finace-app-d638b',
    authDomain: 'finace-app-d638b.firebaseapp.com',
    storageBucket: 'finace-app-d638b.firebasestorage.app',
    measurementId: 'G-MT61SJE64D',
  );
}
